## Importing required packages

In [2]:
import numpy as np
import cv2
from scipy.spatial import distance

In [ ]:
cd /content/drive/MyDrive/TASKS_ML_NETZWERK_ACADAMEY/DL/Social_distance_detection

/content/drive/MyDrive/TASKS_ML_NETZWERK_ACADAMEY/DL/Social_distance_detection


## Loading yolo weights,cfg and coco names

In [3]:
net = cv2.dnn.readNet('yolo/yolov3.weights','yolo/yolov3.cfg')
with open('yolo/coco.names','r')as f:
    classes = [line.strip() for line in f.readlines()]
layer_names = net.getLayerNames()
output_layers = [layer_names[i[0]-1] for i in net.getUnconnectedOutLayers()]
print(output_layers)
print(classes)

['yolo_82', 'yolo_94', 'yolo_106']
['person', 'bicycle', 'car', 'motorbike', 'aeroplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'sofa', 'pottedplant', 'bed', 'diningtable', 'toilet', 'tvmonitor', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush']


## Used Yolo object detection to find only people and returns the confidence, coordinates and centroids of people 

In [4]:
def detect_people(frame, personIndex=0):
    """This function will detects the only people class and it finds the
    confidence,coordinates and centroids of people and returns those values"""
    results = []
    height, width = frame.shape[:2]
    blob = cv2.dnn.blobFromImage(image=frame, scalefactor=1/255.0, size=(416, 416), mean=(0, 0, 0), swapRB=True,
                                 crop=False)
    net.setInput(blob)
    outs = net.forward(output_layers)
    boxes, centroids, confidences = [], [], []
    for out in outs:
        for detection in out:
            scores = detection[5:]
            class_id = np.argmax(scores)
            confidence = scores[class_id]
            if class_id == personIndex and confidence > 0.5:
                center_x = int(detection[0] * width)
                center_y = int(detection[1] * height)
                w = int(detection[2] * width)
                h = int(detection[3] * height)
                x = int(center_x - w / 2)
                y = int(center_y - h / 2)
                boxes.append([x, y, w, h])
                confidences.append(float(confidence))
                centroids.append((center_x, center_y))
    indexes = cv2.dnn.NMSBoxes(boxes, confidences, 0.5, 0.4)
    if len(indexes) > 0:
        for i in indexes.flatten():
            x, y, w, h = (boxes[i][0], boxes[i][1], boxes[i][2], boxes[i][3])
            result = (confidences[i], (x, y, x + w, y + h), centroids[i])
            results.append(result)
    return results


In [4]:
ls

 Social_Distance_Detection.ipynb  'The CCTV People.mp4'   yolo/


## Here it finds the distance between the people, based on distance we will find who is violating social distance

In [7]:
def final(Frame):
    """This function finds the distance between the people,
    based on distance we will find who is violating social distance """
    frame1 = frame.copy()
    results = detect_people(frame1, personIndex=classes.index('person'))
    violate = set()
    if len(results) >= 2:
        centroids = np.array([r[2] for r in results])
        Distance = distance.cdist(centroids, centroids)
        for i in range(Distance.shape[0]):
            for j in range(i + 1, Distance.shape[1]):
                if Distance[i, j] < 85:
                    violate.add(i)
                    violate.add(j)

    for (i, (confi, coordinates, centroid)) in enumerate(results):
        (start_x, start_y, end_x, end_y) = coordinates
        color = (0, 255, 0)
        if i in violate:
            color = (0, 0, 255)
        cv2.rectangle(frame1, (start_x, start_y), (end_x, end_y), color, 2)
    text = f"social distance violations : {len(violate)}"
    # print(frame1)
    o = cv2.putText(frame1, text, (10, frame1.shape[0] - 25), cv2.FONT_HERSHEY_COMPLEX, 0.8, (0, 0, 255), 3)
    return o


## Here we pass input (video file) it will finds the people who is violating and not violating the socal distance and also it saves the video file 

In [6]:
video = cv2.VideoCapture('The CCTV People.mp4')
frame_width = int(video.get(3))
frame_height = int(video.get(4))
size = (frame_width, frame_height)
result_video = cv2.VideoWriter('output2.avi', cv2.VideoWriter_fourcc('M','J','P','G'), 10, size)
while True:
    ret, frame = video.read()
    if ret:
        out_img = final(frame)
        print(out_img)
        cv2.imshow('out',out_img)
        result_video.write(out_img)
        print('writing')
        if cv2.waitKey(1) & 0xff == ord('q'):
            break
    else:
        break
video.release()
result_video.release()
cv2.destroyAllWindows()
print("Done processing video")


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
writing
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
writing
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
writing
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
writing
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
writing
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
writing
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
writing
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
writing
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
writing
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
writing
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]


[[[ 81  31  35]
  [ 79  29  33]
  [ 85  52  53]
  ...
  [ 25  33  37]
  [ 25  33  37]
  [ 25  33  37]]

 [[ 75  25  29]
  [101  51  55]
  [175 142 143]
  ...
  [ 25  33  37]
  [ 25  33  37]
  [ 25  33  37]]

 [[120  70  74]
  [132  82  86]
  [186 153 154]
  ...
  [ 25  33  37]
  [ 25  33  37]
  [ 25  33  37]]

 ...

 [[ 97  93  96]
  [ 97  93  96]
  [ 95  91  94]
  ...
  [116 103  99]
  [118 103  99]
  [118 103  99]]

 [[ 96  92  95]
  [ 97  93  96]
  [ 99  95  98]
  ...
  [114 104  99]
  [116 103  99]
  [116 103  99]]

 [[ 95  91  94]
  [ 98  94  97]
  [ 87  83  86]
  ...
  [114 104  99]
  [116 103  99]
  [116 103  99]]]
writing
[[[ 81  31  35]
  [ 79  29  33]
  [ 85  52  53]
  ...
  [ 25  33  37]
  [ 25  33  37]
  [ 25  33  37]]

 [[ 75  25  29]
  [101  51  55]
  [175 142 143]
  ...
  [ 25  33  37]
  [ 25  33  37]
  [ 25  33  37]]

 [[120  70  74]
  [132  82  86]
  [186 153 154]
  ...
  [ 25  33  37]
  [ 25  33  37]
  [ 25  33  37]]

 ...

 [[ 97  93  96]
  [ 97  93  96]
  [ 95  91  

[[[ 81  31  35]
  [ 79  29  33]
  [ 85  52  53]
  ...
  [ 25  33  37]
  [ 27  35  39]
  [ 27  35  39]]

 [[ 75  25  29]
  [101  51  55]
  [175 142 143]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 [[120  70  74]
  [132  82  86]
  [186 153 154]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 ...

 [[ 99  93  96]
  [ 99  93  96]
  [ 97  91  94]
  ...
  [117 104 100]
  [119 104 100]
  [119 104 100]]

 [[ 99  93  96]
  [100  94  97]
  [101  95  98]
  ...
  [117 104 100]
  [119 104 100]
  [119 104 100]]

 [[ 98  92  95]
  [101  95  98]
  [ 89  83  86]
  ...
  [116 103  99]
  [118 103  99]
  [118 103  99]]]
writing
[[[ 81  31  35]
  [ 79  29  33]
  [ 85  52  53]
  ...
  [ 25  33  37]
  [ 27  35  39]
  [ 27  35  39]]

 [[ 75  25  29]
  [101  51  55]
  [175 142 143]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 [[120  70  74]
  [132  82  86]
  [186 153 154]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 ...

 [[ 99  93  96]
  [ 99  93  96]
  [ 97  91  

[[[ 81  31  35]
  [ 79  29  33]
  [ 85  52  53]
  ...
  [ 25  33  37]
  [ 27  35  39]
  [ 27  35  39]]

 [[ 75  25  29]
  [101  51  55]
  [175 142 143]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 [[120  70  74]
  [132  82  86]
  [186 153 154]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 ...

 [[ 99  93  96]
  [ 99  93  96]
  [ 97  91  94]
  ...
  [111 103  98]
  [114 104  99]
  [114 104  99]]

 [[ 99  93  96]
  [100  94  97]
  [101  95  98]
  ...
  [109 103  98]
  [112 104  99]
  [112 104  99]]

 [[ 98  92  95]
  [101  95  98]
  [ 89  83  86]
  ...
  [109 103  98]
  [112 104  99]
  [112 104  99]]]
writing
[[[ 81  31  35]
  [ 79  29  33]
  [ 85  52  53]
  ...
  [ 25  33  37]
  [ 27  35  39]
  [ 27  35  39]]

 [[ 75  25  29]
  [101  51  55]
  [175 142 143]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 [[120  70  74]
  [132  82  86]
  [186 153 154]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 ...

 [[ 99  93  96]
  [ 99  93  96]
  [ 97  91  

[[[ 72  27  30]
  [ 75  30  33]
  [ 76  50  50]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 [[ 69  24  27]
  [ 93  48  51]
  [168 142 142]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 [[126  81  84]
  [128  83  86]
  [180 154 154]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 ...

 [[105 100 106]
  [ 95  90  96]
  [ 99  94 100]
  ...
  [115 102  98]
  [116 103  99]
  [116 103  99]]

 [[ 93  88  94]
  [ 93  88  94]
  [100  95 101]
  ...
  [115 102  98]
  [116 103  99]
  [116 103  99]]

 [[ 96  91  97]
  [103  98 104]
  [ 91  86  92]
  ...
  [115 102  98]
  [116 103  99]
  [116 103  99]]]
writing
[[[ 72  27  30]
  [ 75  30  33]
  [ 76  50  50]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 [[ 69  24  27]
  [ 93  48  51]
  [168 142 142]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 [[126  81  84]
  [128  83  86]
  [180 154 154]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 ...

 [[105 100 106]
  [ 95  90  96]
  [ 99  94 1

[[[ 72  27  30]
  [ 75  30  33]
  [ 76  50  50]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 [[ 69  24  27]
  [ 93  48  51]
  [168 142 142]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 [[126  81  84]
  [128  83  86]
  [180 154 154]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 ...

 [[105 100 106]
  [ 95  90  96]
  [ 99  94 100]
  ...
  [113 107 102]
  [113 107 102]
  [113 107 102]]

 [[ 93  88  94]
  [ 93  88  94]
  [100  95 101]
  ...
  [114 108 103]
  [114 108 103]
  [114 108 103]]

 [[ 96  91  97]
  [103  98 104]
  [ 91  86  92]
  ...
  [114 108 103]
  [115 109 104]
  [115 109 104]]]
writing
[[[ 72  27  30]
  [ 75  30  33]
  [ 76  50  50]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 [[ 69  24  27]
  [ 93  48  51]
  [168 142 142]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 [[126  81  84]
  [128  83  86]
  [180 154 154]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 ...

 [[105 101 104]
  [ 95  91  94]
  [ 99  95  

[[[ 72  27  30]
  [ 75  30  33]
  [ 76  50  50]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 [[ 69  24  27]
  [ 93  48  51]
  [168 142 142]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 [[126  81  84]
  [128  83  86]
  [180 154 154]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 ...

 [[105 101 104]
  [ 95  91  94]
  [ 99  95  98]
  ...
  [117 109  99]
  [118 110 100]
  [118 110 100]]

 [[ 93  89  92]
  [ 93  89  92]
  [100  96  99]
  ...
  [115 109  99]
  [116 110 100]
  [116 110 100]]

 [[ 97  93  96]
  [103  99 102]
  [ 91  87  90]
  ...
  [116 110 100]
  [117 111 101]
  [117 111 101]]]
writing
[[[ 72  27  30]
  [ 75  30  33]
  [ 76  50  50]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 [[ 69  24  27]
  [ 93  48  51]
  [168 142 142]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 [[126  81  84]
  [128  83  86]
  [180 154 154]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 ...

 [[105 101 104]
  [ 95  91  94]
  [ 99  95  

[[[ 72  27  30]
  [ 75  30  33]
  [ 76  50  50]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 [[ 69  24  27]
  [ 93  48  51]
  [168 142 142]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 [[126  81  84]
  [128  83  86]
  [180 154 154]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 ...

 [[105 102 103]
  [ 95  92  93]
  [ 99  96  97]
  ...
  [118 109 101]
  [118 109 101]
  [118 109 101]]

 [[ 93  90  91]
  [ 93  90  91]
  [100  97  98]
  ...
  [116 109 101]
  [116 109 101]
  [116 109 101]]

 [[ 97  94  95]
  [103 100 101]
  [ 91  88  89]
  ...
  [116 109 101]
  [116 109 101]
  [116 109 101]]]
writing
[[[ 72  27  30]
  [ 75  30  33]
  [ 76  50  50]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 [[ 69  24  27]
  [ 93  48  51]
  [168 142 142]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 [[126  81  84]
  [128  83  86]
  [180 154 154]
  ...
  [ 27  35  39]
  [ 27  35  39]
  [ 27  35  39]]

 ...

 [[105 102 103]
  [ 95  92  93]
  [ 99  96  

[[[ 72  27  30]
  [ 75  30  33]
  [ 76  50  50]
  ...
  [ 27  35  39]
  [ 28  36  40]
  [ 28  36  40]]

 [[ 69  24  27]
  [ 93  48  51]
  [168 142 142]
  ...
  [ 28  36  40]
  [ 28  36  40]
  [ 28  36  40]]

 [[126  81  84]
  [128  83  86]
  [180 154 154]
  ...
  [ 28  36  40]
  [ 28  36  40]
  [ 28  36  40]]

 ...

 [[105 101 104]
  [ 95  91  94]
  [ 99  95  98]
  ...
  [118 109 101]
  [118 109 101]
  [118 109 101]]

 [[ 93  89  92]
  [ 93  89  92]
  [100  96  99]
  ...
  [116 109 101]
  [116 109 101]
  [116 109 101]]

 [[ 97  93  96]
  [103  99 102]
  [ 91  87  90]
  ...
  [116 109 101]
  [116 109 101]
  [116 109 101]]]
writing
[[[ 72  27  30]
  [ 75  30  33]
  [ 76  50  50]
  ...
  [ 27  35  39]
  [ 28  36  40]
  [ 28  36  40]]

 [[ 69  24  27]
  [ 93  48  51]
  [168 142 142]
  ...
  [ 28  36  40]
  [ 28  36  40]
  [ 28  36  40]]

 [[126  81  84]
  [128  83  86]
  [180 154 154]
  ...
  [ 28  36  40]
  [ 28  36  40]
  [ 28  36  40]]

 ...

 [[105 101 104]
  [ 95  91  94]
  [ 99  95  

[[[ 72  27  30]
  [ 75  30  33]
  [ 76  50  50]
  ...
  [ 27  35  39]
  [ 28  36  40]
  [ 28  36  40]]

 [[ 69  24  27]
  [ 93  48  51]
  [168 142 142]
  ...
  [ 28  36  40]
  [ 28  36  40]
  [ 28  36  40]]

 [[126  81  84]
  [128  83  86]
  [180 154 154]
  ...
  [ 28  36  40]
  [ 28  36  40]
  [ 28  36  40]]

 ...

 [[105 101 104]
  [ 95  91  94]
  [ 99  95  98]
  ...
  [116 108 103]
  [116 108 103]
  [116 108 103]]

 [[ 93  89  92]
  [ 93  89  92]
  [100  96  99]
  ...
  [118 108 103]
  [118 108 103]
  [118 108 103]]

 [[ 97  93  96]
  [103  99 102]
  [ 91  87  90]
  ...
  [118 108 103]
  [118 108 103]
  [118 108 103]]]
writing
[[[ 72  27  30]
  [ 75  30  33]
  [ 76  50  50]
  ...
  [ 27  35  39]
  [ 28  36  40]
  [ 28  36  40]]

 [[ 69  24  27]
  [ 93  48  51]
  [168 142 142]
  ...
  [ 28  36  40]
  [ 28  36  40]
  [ 28  36  40]]

 [[126  81  84]
  [128  83  86]
  [180 154 154]
  ...
  [ 28  36  40]
  [ 28  36  40]
  [ 28  36  40]]

 ...

 [[105 101 104]
  [ 95  91  94]
  [ 99  95  

[[[ 72  27  30]
  [ 75  30  33]
  [ 76  50  50]
  ...
  [ 23  31  35]
  [ 24  32  36]
  [ 24  32  36]]

 [[ 69  24  27]
  [ 93  48  51]
  [168 142 142]
  ...
  [ 24  32  36]
  [ 24  32  36]
  [ 24  32  36]]

 [[126  81  84]
  [128  83  86]
  [180 154 154]
  ...
  [ 24  32  36]
  [ 24  32  36]
  [ 24  32  36]]

 ...

 [[ 70  66  69]
  [ 59  55  58]
  [ 64  60  63]
  ...
  [114 108 103]
  [114 108 103]
  [114 108 103]]

 [[ 59  55  58]
  [ 59  55  58]
  [ 66  62  65]
  ...
  [114 108 103]
  [114 108 103]
  [114 108 103]]

 [[ 61  57  60]
  [ 68  64  67]
  [ 56  52  55]
  ...
  [114 108 103]
  [114 108 103]
  [114 108 103]]]
writing
[[[ 72  27  30]
  [ 75  30  33]
  [ 76  50  50]
  ...
  [ 23  31  35]
  [ 24  32  36]
  [ 24  32  36]]

 [[ 69  24  27]
  [ 93  48  51]
  [168 142 142]
  ...
  [ 24  32  36]
  [ 24  32  36]
  [ 24  32  36]]

 [[126  81  84]
  [128  83  86]
  [180 154 154]
  ...
  [ 24  32  36]
  [ 24  32  36]
  [ 24  32  36]]

 ...

 [[ 70  66  69]
  [ 59  55  58]
  [ 64  60  

[[[ 72  27  30]
  [ 75  30  33]
  [ 76  50  50]
  ...
  [ 23  31  35]
  [ 24  32  36]
  [ 24  32  36]]

 [[ 69  24  27]
  [ 93  48  51]
  [168 142 142]
  ...
  [ 24  32  36]
  [ 24  32  36]
  [ 24  32  36]]

 [[126  81  84]
  [128  83  86]
  [180 154 154]
  ...
  [ 24  32  36]
  [ 24  32  36]
  [ 24  32  36]]

 ...

 [[ 88  87  89]
  [ 85  84  86]
  [ 83  82  84]
  ...
  [111 103  98]
  [111 103  98]
  [111 103  98]]

 [[ 88  87  89]
  [ 86  85  87]
  [ 82  81  83]
  ...
  [111 103  98]
  [111 103  98]
  [111 103  98]]

 [[ 86  85  87]
  [ 85  84  86]
  [ 85  84  86]
  ...
  [112 104  99]
  [112 104  99]
  [112 104  99]]]
writing
[[[ 72  27  30]
  [ 75  30  33]
  [ 76  50  50]
  ...
  [ 23  31  35]
  [ 24  32  36]
  [ 24  32  36]]

 [[ 69  24  27]
  [ 93  48  51]
  [168 142 142]
  ...
  [ 24  32  36]
  [ 24  32  36]
  [ 24  32  36]]

 [[126  81  84]
  [128  83  86]
  [180 154 154]
  ...
  [ 24  32  36]
  [ 24  32  36]
  [ 24  32  36]]

 ...

 [[ 90  89  91]
  [ 87  86  88]
  [ 83  82  

[[[ 72  27  30]
  [ 75  30  33]
  [ 76  50  50]
  ...
  [ 24  32  36]
  [ 24  32  36]
  [ 24  32  36]]

 [[ 69  24  27]
  [ 93  48  51]
  [168 142 142]
  ...
  [ 24  32  36]
  [ 24  32  36]
  [ 24  32  36]]

 [[126  81  84]
  [128  83  86]
  [180 154 154]
  ...
  [ 24  32  36]
  [ 24  32  36]
  [ 24  32  36]]

 ...

 [[ 93  89  92]
  [ 90  86  89]
  [ 87  83  86]
  ...
  [111 103  98]
  [111 103  98]
  [111 103  98]]

 [[ 91  87  90]
  [ 89  85  88]
  [ 85  81  84]
  ...
  [111 103  98]
  [111 103  98]
  [111 103  98]]

 [[ 89  85  88]
  [ 88  84  87]
  [ 87  83  86]
  ...
  [112 104  99]
  [112 104  99]
  [112 104  99]]]
writing
[[[ 72  27  30]
  [ 75  30  33]
  [ 76  50  50]
  ...
  [ 24  32  36]
  [ 24  32  36]
  [ 24  32  36]]

 [[ 69  24  27]
  [ 93  48  51]
  [168 142 142]
  ...
  [ 24  32  36]
  [ 24  32  36]
  [ 24  32  36]]

 [[126  81  84]
  [128  83  86]
  [180 154 154]
  ...
  [ 24  32  36]
  [ 24  32  36]
  [ 24  32  36]]

 ...

 [[ 93  89  92]
  [ 90  86  89]
  [ 87  83  

[[[ 76  30  36]
  [ 88  42  48]
  [ 73  49  51]
  ...
  [ 29  35  39]
  [ 27  33  37]
  [ 27  33  37]]

 [[ 81  35  41]
  [103  57  63]
  [163 139 141]
  ...
  [ 27  33  37]
  [ 27  33  37]
  [ 27  33  37]]

 [[125  79  85]
  [128  82  88]
  [178 154 156]
  ...
  [ 27  33  37]
  [ 27  33  37]
  [ 27  33  37]]

 ...

 [[ 78  76  81]
  [ 78  76  81]
  [ 75  73  78]
  ...
  [107 103  99]
  [107 103  99]
  [107 103  99]]

 [[ 72  70  75]
  [ 72  70  75]
  [ 69  67  72]
  ...
  [107 103  99]
  [107 103  99]
  [107 103  99]]

 [[ 67  65  70]
  [ 67  65  70]
  [ 65  63  68]
  ...
  [108 104 100]
  [108 104 100]
  [108 104 100]]]
writing
[[[ 76  30  36]
  [ 88  42  48]
  [ 73  49  51]
  ...
  [ 29  35  39]
  [ 27  33  37]
  [ 27  33  37]]

 [[ 81  35  41]
  [103  57  63]
  [163 139 141]
  ...
  [ 27  33  37]
  [ 27  33  37]
  [ 27  33  37]]

 [[125  79  85]
  [128  82  88]
  [178 154 156]
  ...
  [ 27  33  37]
  [ 27  33  37]
  [ 27  33  37]]

 ...

 [[ 78  76  81]
  [ 78  76  81]
  [ 75  73  

[[[ 76  30  36]
  [ 88  42  48]
  [ 73  49  51]
  ...
  [ 23  29  33]
  [ 23  29  33]
  [ 23  29  33]]

 [[ 81  35  41]
  [103  57  63]
  [163 139 141]
  ...
  [ 23  29  33]
  [ 23  29  33]
  [ 23  29  33]]

 [[125  79  85]
  [128  82  88]
  [178 154 156]
  ...
  [ 23  29  33]
  [ 23  29  33]
  [ 23  29  33]]

 ...

 [[ 80  83  88]
  [ 80  83  88]
  [ 77  80  85]
  ...
  [109 102  94]
  [109 102  94]
  [109 102  94]]

 [[ 81  84  89]
  [ 81  84  89]
  [ 77  80  85]
  ...
  [109 102  94]
  [109 102  94]
  [109 102  94]]

 [[ 83  86  91]
  [ 82  85  90]
  [ 77  80  85]
  ...
  [109 102  94]
  [109 102  94]
  [109 102  94]]]
writing
[[[ 76  30  36]
  [ 88  42  48]
  [ 73  49  51]
  ...
  [ 23  29  33]
  [ 23  29  33]
  [ 23  29  33]]

 [[ 81  35  41]
  [103  57  63]
  [163 139 141]
  ...
  [ 23  29  33]
  [ 23  29  33]
  [ 23  29  33]]

 [[125  79  85]
  [128  82  88]
  [178 154 156]
  ...
  [ 23  29  33]
  [ 23  29  33]
  [ 23  29  33]]

 ...

 [[ 82  83  88]
  [ 82  83  88]
  [ 79  80  

[[[ 76  30  36]
  [ 88  42  48]
  [ 73  49  51]
  ...
  [ 23  29  33]
  [ 23  29  33]
  [ 23  29  33]]

 [[ 81  35  41]
  [103  57  63]
  [163 139 141]
  ...
  [ 23  29  33]
  [ 23  29  33]
  [ 23  29  33]]

 [[125  79  85]
  [128  82  88]
  [178 154 156]
  ...
  [ 23  29  33]
  [ 23  29  33]
  [ 23  29  33]]

 ...

 [[ 91  89  94]
  [ 91  89  94]
  [ 89  87  92]
  ...
  [105 101  97]
  [105 101  97]
  [105 101  97]]

 [[ 91  89  94]
  [ 90  88  93]
  [ 87  85  90]
  ...
  [105 101  97]
  [105 101  97]
  [105 101  97]]

 [[ 91  89  94]
  [ 90  88  93]
  [ 86  84  89]
  ...
  [105 101  97]
  [105 101  97]
  [105 101  97]]]
writing
[[[ 76  30  36]
  [ 88  42  48]
  [ 73  49  51]
  ...
  [ 23  29  33]
  [ 23  29  33]
  [ 23  29  33]]

 [[ 81  35  41]
  [103  57  63]
  [163 139 141]
  ...
  [ 23  29  33]
  [ 23  29  33]
  [ 23  29  33]]

 [[125  79  85]
  [128  82  88]
  [178 154 156]
  ...
  [ 23  29  33]
  [ 23  29  33]
  [ 23  29  33]]

 ...

 [[ 91  89  94]
  [ 91  89  94]
  [ 89  87  

[[[ 76  30  36]
  [ 88  42  48]
  [ 73  49  51]
  ...
  [ 25  33  32]
  [ 25  33  32]
  [ 25  33  32]]

 [[ 81  35  41]
  [103  57  63]
  [163 139 141]
  ...
  [ 25  33  32]
  [ 25  33  32]
  [ 25  33  32]]

 [[125  79  85]
  [128  82  88]
  [178 154 156]
  ...
  [ 25  33  32]
  [ 25  33  32]
  [ 25  33  32]]

 ...

 [[ 91  89  94]
  [ 91  89  94]
  [ 89  87  92]
  ...
  [112 103 100]
  [113 104 101]
  [113 104 101]]

 [[ 91  89  94]
  [ 90  88  93]
  [ 87  85  90]
  ...
  [113 104 101]
  [115 106 103]
  [115 106 103]]

 [[ 91  89  94]
  [ 90  88  93]
  [ 86  84  89]
  ...
  [113 104 101]
  [116 107 104]
  [116 107 104]]]
writing
[[[ 76  30  36]
  [ 88  42  48]
  [ 73  49  51]
  ...
  [ 25  33  32]
  [ 25  33  32]
  [ 25  33  32]]

 [[ 81  35  41]
  [103  57  63]
  [163 139 141]
  ...
  [ 25  33  32]
  [ 25  33  32]
  [ 25  33  32]]

 [[125  79  85]
  [128  82  88]
  [178 154 156]
  ...
  [ 25  33  32]
  [ 25  33  32]
  [ 25  33  32]]

 ...

 [[ 91  89  94]
  [ 91  89  94]
  [ 89  87  

[[[ 76  30  36]
  [ 88  42  48]
  [ 73  49  51]
  ...
  [ 25  33  32]
  [ 25  33  32]
  [ 25  33  32]]

 [[ 81  35  41]
  [103  57  63]
  [163 139 141]
  ...
  [ 25  33  32]
  [ 25  33  32]
  [ 25  33  32]]

 [[125  79  85]
  [128  82  88]
  [178 154 156]
  ...
  [ 25  33  32]
  [ 25  33  32]
  [ 25  33  32]]

 ...

 [[ 63  51  58]
  [ 88  76  83]
  [106  94 101]
  ...
  [112 103 100]
  [113 104 101]
  [113 104 101]]

 [[ 46  34  41]
  [ 70  58  65]
  [ 89  77  84]
  ...
  [113 104 101]
  [115 106 103]
  [115 106 103]]

 [[ 37  25  32]
  [ 61  49  56]
  [ 80  68  75]
  ...
  [113 104 101]
  [116 107 104]
  [116 107 104]]]
writing
[[[ 76  30  36]
  [ 88  42  48]
  [ 73  49  51]
  ...
  [ 25  33  32]
  [ 25  33  32]
  [ 25  33  32]]

 [[ 81  35  41]
  [103  57  63]
  [163 139 141]
  ...
  [ 25  33  32]
  [ 25  33  32]
  [ 25  33  32]]

 [[125  79  85]
  [128  82  88]
  [178 154 156]
  ...
  [ 25  33  32]
  [ 25  33  32]
  [ 25  33  32]]

 ...

 [[ 63  51  58]
  [ 88  76  83]
  [106  94 1

[[[ 76  30  36]
  [ 88  42  48]
  [ 73  49  51]
  ...
  [ 25  33  32]
  [ 25  33  32]
  [ 25  33  32]]

 [[ 81  35  41]
  [103  57  63]
  [163 139 141]
  ...
  [ 25  33  32]
  [ 25  33  32]
  [ 25  33  32]]

 [[125  79  85]
  [128  82  88]
  [178 154 156]
  ...
  [ 25  33  32]
  [ 25  33  32]
  [ 25  33  32]]

 ...

 [[ 94  87  93]
  [ 97  90  96]
  [ 95  88  94]
  ...
  [116 107 104]
  [116 107 104]
  [116 107 104]]

 [[ 92  85  91]
  [ 95  88  94]
  [ 92  85  91]
  ...
  [116 107 104]
  [116 107 104]
  [116 107 104]]

 [[ 91  84  90]
  [ 95  88  94]
  [ 90  83  89]
  ...
  [116 107 104]
  [116 107 104]
  [116 107 104]]]
writing
[[[ 76  30  36]
  [ 88  42  48]
  [ 73  49  51]
  ...
  [ 25  33  32]
  [ 25  33  32]
  [ 25  33  32]]

 [[ 81  35  41]
  [103  57  63]
  [163 139 141]
  ...
  [ 25  33  32]
  [ 25  33  32]
  [ 25  33  32]]

 [[125  79  85]
  [128  82  88]
  [178 154 156]
  ...
  [ 25  33  32]
  [ 25  33  32]
  [ 25  33  32]]

 ...

 [[ 94  87  93]
  [ 97  90  96]
  [ 95  88  

[[[ 76  30  36]
  [ 88  42  48]
  [ 73  49  51]
  ...
  [ 25  33  32]
  [ 25  33  32]
  [ 25  33  32]]

 [[ 81  35  41]
  [103  57  63]
  [163 139 141]
  ...
  [ 25  33  32]
  [ 25  33  32]
  [ 25  33  32]]

 [[125  79  85]
  [128  82  88]
  [178 154 156]
  ...
  [ 25  33  32]
  [ 25  33  32]
  [ 25  33  32]]

 ...

 [[ 13  12  14]
  [  8   7   9]
  [ 16  15  17]
  ...
  [116 107 104]
  [116 107 104]
  [116 107 104]]

 [[ 15  14  16]
  [ 10   9  11]
  [ 16  15  17]
  ...
  [116 107 104]
  [116 107 104]
  [116 107 104]]

 [[ 16  15  17]
  [ 11  10  12]
  [ 17  16  18]
  ...
  [116 107 104]
  [116 107 104]
  [116 107 104]]]
writing
[[[ 76  30  36]
  [ 88  42  48]
  [ 73  49  51]
  ...
  [ 24  30  34]
  [ 24  30  34]
  [ 24  30  34]]

 [[ 81  35  41]
  [103  57  63]
  [163 139 141]
  ...
  [ 24  30  34]
  [ 24  30  34]
  [ 24  30  34]]

 [[125  79  85]
  [128  82  88]
  [178 154 156]
  ...
  [ 24  30  34]
  [ 24  30  34]
  [ 24  30  34]]

 ...

 [[ 25  15  22]
  [ 25  15  22]
  [ 30  20  

[[[ 76  30  36]
  [ 88  42  48]
  [ 73  49  51]
  ...
  [ 24  30  34]
  [ 24  30  34]
  [ 24  30  34]]

 [[ 81  35  41]
  [103  57  63]
  [163 139 141]
  ...
  [ 24  30  34]
  [ 24  30  34]
  [ 24  30  34]]

 [[125  79  85]
  [128  82  88]
  [178 154 156]
  ...
  [ 24  30  34]
  [ 24  30  34]
  [ 24  30  34]]

 ...

 [[ 92  87  88]
  [ 94  89  90]
  [ 93  88  89]
  ...
  [116 107 104]
  [116 107 104]
  [116 107 104]]

 [[101  96  97]
  [ 94  89  90]
  [102  97  98]
  ...
  [116 107 104]
  [116 107 104]
  [116 107 104]]

 [[ 94  89  90]
  [101  96  97]
  [107 102 103]
  ...
  [116 107 104]
  [116 107 104]
  [116 107 104]]]
writing
[[[ 76  30  36]
  [ 88  42  48]
  [ 73  49  51]
  ...
  [ 24  30  34]
  [ 24  30  34]
  [ 24  30  34]]

 [[ 81  35  41]
  [103  57  63]
  [163 139 141]
  ...
  [ 24  30  34]
  [ 24  30  34]
  [ 24  30  34]]

 [[125  79  85]
  [128  82  88]
  [178 154 156]
  ...
  [ 24  30  34]
  [ 24  30  34]
  [ 24  30  34]]

 ...

 [[ 92  87  88]
  [ 94  89  90]
  [ 93  88  

[[[ 76  30  36]
  [ 88  42  48]
  [ 73  49  51]
  ...
  [ 24  30  34]
  [ 24  30  34]
  [ 24  30  34]]

 [[ 81  35  41]
  [103  57  63]
  [163 139 141]
  ...
  [ 24  30  34]
  [ 24  30  34]
  [ 24  30  34]]

 [[125  79  85]
  [128  82  88]
  [178 154 156]
  ...
  [ 24  30  34]
  [ 24  30  34]
  [ 24  30  34]]

 ...

 [[ 92  87  88]
  [ 94  89  90]
  [ 93  88  89]
  ...
  [116 107 104]
  [116 107 104]
  [116 107 104]]

 [[100  95  96]
  [ 95  90  91]
  [102  97  98]
  ...
  [116 107 104]
  [116 107 104]
  [116 107 104]]

 [[ 98  93  94]
  [101  96  97]
  [105 100 101]
  ...
  [116 107 104]
  [116 107 104]
  [116 107 104]]]
writing
[[[ 76  30  36]
  [ 88  42  48]
  [ 73  49  51]
  ...
  [ 24  30  34]
  [ 24  30  34]
  [ 24  30  34]]

 [[ 81  35  41]
  [103  57  63]
  [163 139 141]
  ...
  [ 24  30  34]
  [ 24  30  34]
  [ 24  30  34]]

 [[125  79  85]
  [128  82  88]
  [178 154 156]
  ...
  [ 24  30  34]
  [ 24  30  34]
  [ 24  30  34]]

 ...

 [[ 16  11  12]
  [ 23  18  19]
  [ 27  22  

[[[ 76  30  36]
  [ 88  42  48]
  [ 73  49  51]
  ...
  [ 22  28  32]
  [ 22  28  32]
  [ 22  28  32]]

 [[ 81  35  41]
  [103  57  63]
  [163 139 141]
  ...
  [ 23  29  33]
  [ 22  28  32]
  [ 22  28  32]]

 [[125  79  85]
  [128  82  88]
  [178 154 156]
  ...
  [ 22  28  32]
  [ 22  28  32]
  [ 22  28  32]]

 ...

 [[ 21  25  20]
  [ 29  33  28]
  [ 45  49  44]
  ...
  [116 107 104]
  [116 107 104]
  [116 107 104]]

 [[ 23  27  22]
  [ 28  32  27]
  [ 44  48  43]
  ...
  [116 107 104]
  [116 107 104]
  [116 107 104]]

 [[ 23  27  22]
  [ 28  32  27]
  [ 44  48  43]
  ...
  [116 107 104]
  [116 107 104]
  [116 107 104]]]
writing
[[[ 76  30  36]
  [ 88  42  48]
  [ 73  49  51]
  ...
  [ 22  28  32]
  [ 22  28  32]
  [ 22  28  32]]

 [[ 81  35  41]
  [103  57  63]
  [163 139 141]
  ...
  [ 23  29  33]
  [ 22  28  32]
  [ 22  28  32]]

 [[125  79  85]
  [128  82  88]
  [178 154 156]
  ...
  [ 22  28  32]
  [ 22  28  32]
  [ 22  28  32]]

 ...

 [[ 16  20  15]
  [ 16  20  15]
  [ 17  21  

[[[ 66  19  22]
  [ 77  30  33]
  [ 74  43  44]
  ...
  [ 29  32  37]
  [ 28  31  36]
  [ 27  30  35]]

 [[ 73  26  29]
  [ 87  40  43]
  [170 139 140]
  ...
  [ 29  32  37]
  [ 28  31  36]
  [ 27  30  35]]

 [[119  81  83]
  [126  88  90]
  [169 148 147]
  ...
  [ 27  30  35]
  [ 27  30  35]
  [ 27  30  35]]

 ...

 [[ 93  88  89]
  [ 94  89  90]
  [ 94  89  90]
  ...
  [109 106 100]
  [109 106 100]
  [109 106 100]]

 [[ 78  70  72]
  [ 92  84  86]
  [ 95  90  91]
  ...
  [111 105 100]
  [113 105 100]
  [113 105 100]]

 [[ 82  74  76]
  [ 92  84  86]
  [ 78  73  74]
  ...
  [111 105 100]
  [113 105 100]
  [113 105 100]]]
writing
[[[ 66  19  22]
  [ 77  30  33]
  [ 74  43  44]
  ...
  [ 29  32  37]
  [ 28  31  36]
  [ 27  30  35]]

 [[ 73  26  29]
  [ 87  40  43]
  [170 139 140]
  ...
  [ 29  32  37]
  [ 28  31  36]
  [ 27  30  35]]

 [[119  81  83]
  [126  88  90]
  [169 148 147]
  ...
  [ 27  30  35]
  [ 27  30  35]
  [ 27  30  35]]

 ...

 [[ 95  89  92]
  [ 97  91  94]
  [ 97  91  

[[[ 66  19  22]
  [ 77  30  33]
  [ 74  43  44]
  ...
  [ 29  32  37]
  [ 28  31  36]
  [ 27  30  35]]

 [[ 73  26  29]
  [ 87  40  43]
  [170 139 140]
  ...
  [ 29  32  37]
  [ 28  31  36]
  [ 27  30  35]]

 [[119  81  83]
  [126  88  90]
  [169 148 147]
  ...
  [ 27  30  35]
  [ 27  30  35]
  [ 27  30  35]]

 ...

 [[ 99  94  93]
  [ 99  94  93]
  [ 99  94  93]
  ...
  [106 104 100]
  [106 104 100]
  [106 104 100]]

 [[ 84  76  76]
  [ 99  91  91]
  [101  96  95]
  ...
  [107 105 101]
  [107 105 101]
  [107 105 101]]

 [[ 88  80  80]
  [ 97  89  89]
  [ 84  79  78]
  ...
  [109 107 103]
  [109 107 103]
  [109 107 103]]]
writing
[[[ 66  19  22]
  [ 77  30  33]
  [ 74  43  44]
  ...
  [ 29  32  37]
  [ 28  31  36]
  [ 27  30  35]]

 [[ 73  26  29]
  [ 87  40  43]
  [170 139 140]
  ...
  [ 29  32  37]
  [ 28  31  36]
  [ 27  30  35]]

 [[119  81  83]
  [126  88  90]
  [169 148 147]
  ...
  [ 27  30  35]
  [ 27  30  35]
  [ 27  30  35]]

 ...

 [[ 99  94  93]
  [ 99  94  93]
  [ 99  94  

[[[ 66  19  22]
  [ 77  30  33]
  [ 74  43  44]
  ...
  [ 29  32  37]
  [ 28  31  36]
  [ 27  30  35]]

 [[ 73  26  29]
  [ 87  40  43]
  [170 139 140]
  ...
  [ 28  31  36]
  [ 28  31  36]
  [ 27  30  35]]

 [[119  81  83]
  [126  88  90]
  [169 148 147]
  ...
  [ 28  31  36]
  [ 27  30  35]
  [ 27  30  35]]

 ...

 [[102  97  96]
  [101  96  95]
  [102  97  96]
  ...
  [111 105 100]
  [111 105 100]
  [111 105 100]]

 [[ 87  79  79]
  [102  94  94]
  [105 100  99]
  ...
  [111 105 100]
  [111 105 100]
  [111 105 100]]

 [[ 94  86  86]
  [102  94  94]
  [ 87  82  81]
  ...
  [111 105 100]
  [111 105 100]
  [111 105 100]]]
writing
[[[ 66  19  22]
  [ 77  30  33]
  [ 74  43  44]
  ...
  [ 29  32  37]
  [ 28  31  36]
  [ 27  30  35]]

 [[ 73  26  29]
  [ 87  40  43]
  [170 139 140]
  ...
  [ 28  31  36]
  [ 28  31  36]
  [ 27  30  35]]

 [[119  81  83]
  [126  88  90]
  [169 148 147]
  ...
  [ 28  31  36]
  [ 27  30  35]
  [ 27  30  35]]

 ...

 [[102  97  96]
  [101  96  95]
  [102  97  

[[[ 73  26  29]
  [ 84  37  40]
  [ 81  50  51]
  ...
  [ 29  32  37]
  [ 28  31  36]
  [ 27  30  35]]

 [[ 79  32  35]
  [ 93  46  49]
  [176 145 146]
  ...
  [ 28  31  36]
  [ 28  31  36]
  [ 27  30  35]]

 [[120  82  84]
  [127  89  91]
  [170 149 148]
  ...
  [ 28  31  36]
  [ 27  30  35]
  [ 27  30  35]]

 ...

 [[100 100  98]
  [ 98  98  96]
  [ 98  98  96]
  ...
  [111 105 100]
  [111 105 100]
  [111 105 100]]

 [[ 88  85  84]
  [103 100  99]
  [105 105 103]
  ...
  [111 105 100]
  [111 105 100]
  [111 105 100]]

 [[ 97  94  93]
  [104 101 100]
  [ 90  90  88]
  ...
  [111 105 100]
  [111 105 100]
  [111 105 100]]]
writing
[[[ 73  26  29]
  [ 84  37  40]
  [ 81  50  51]
  ...
  [ 29  32  37]
  [ 28  31  36]
  [ 27  30  35]]

 [[ 79  32  35]
  [ 93  46  49]
  [176 145 146]
  ...
  [ 28  31  36]
  [ 28  31  36]
  [ 27  30  35]]

 [[120  82  84]
  [127  89  91]
  [170 149 148]
  ...
  [ 28  31  36]
  [ 27  30  35]
  [ 27  30  35]]

 ...

 [[100 100  98]
  [ 98  98  96]
  [ 98  98  

[[[ 73  26  29]
  [ 84  37  40]
  [ 81  50  51]
  ...
  [ 29  32  37]
  [ 29  32  37]
  [ 29  32  37]]

 [[ 79  32  35]
  [ 93  46  49]
  [176 145 146]
  ...
  [ 29  32  37]
  [ 29  32  37]
  [ 29  32  37]]

 [[120  82  84]
  [127  89  91]
  [170 149 148]
  ...
  [ 29  32  37]
  [ 29  32  37]
  [ 29  32  37]]

 ...

 [[100 100  98]
  [ 98  98  96]
  [100 100  98]
  ...
  [111 105 100]
  [111 105 100]
  [111 105 100]]

 [[ 88  85  84]
  [102  99  98]
  [105 105 103]
  ...
  [111 105 100]
  [111 105 100]
  [111 105 100]]

 [[ 97  94  93]
  [103 100  99]
  [ 90  90  88]
  ...
  [111 105 100]
  [111 105 100]
  [111 105 100]]]
writing
[[[ 73  26  29]
  [ 84  37  40]
  [ 81  50  51]
  ...
  [ 29  32  37]
  [ 29  32  37]
  [ 29  32  37]]

 [[ 79  32  35]
  [ 93  46  49]
  [176 145 146]
  ...
  [ 29  32  37]
  [ 29  32  37]
  [ 29  32  37]]

 [[120  82  84]
  [127  89  91]
  [170 149 148]
  ...
  [ 29  32  37]
  [ 29  32  37]
  [ 29  32  37]]

 ...

 [[100 100  98]
  [ 98  98  96]
  [100 100  